layout={
  main={
    LinearLayoutCompat;
    orientation="vertical",
  },
  dlg={
    LinearLayoutCompat;
    orientation="vertical",
    {
      TextView,
      id="label",
    },
    {
      EditText,
      id="fld",
      layout_width="fill",
    },
    {
      Button,
      --text="确定";
      text=gets("ok_button"),
      onClick="ok",
    },
  },
  ck={
    LinearLayoutCompat;
    orientation="vertical";
    {
      RadioGroup;
      layout_weight="1";
      id="ck_rg";
    };
    {
      Button;
      --text="确定";
      text=gets("ok_button"),
      id="ck_bt",
    };
  };
}