editor_sidebar={
  left_sidebar={
    LinearLayoutCompat;
    layout_width="fill";
    layout_height="fill";
    orientation="vertical";
    {
      LinearLayoutCompat;
      id="left_sidebar_title_bar";
      layout_width="fill";
      layout_height="56dp";
      orientation="horizontal";
      backgroundColor=get_theme_color("tool_bar_color");
      layout_marginBottom="6dp";
      paddingTop="6dp";
      {
        LinearLayoutCompat;
        layout_weight="1";
        gravity="center";
        layout_height="fill";
        orientation="vertical";
        {
          TextView;
          id="last_one_path";
          Visibility="8";
          text="0";
        };
        {
          TextView;
          ellipsize="end";
          textColor=system_title_color();--标题颜色
          Typeface=load_font("common");
          gravity="center";
          singleLine="true";
          layout_marginLeft="16dp";
          text=gets("project_not_open");--未打开工程
          id="ch_project_path";
          layout_gravity="left";
          textSize="18sp";
          layout_marginRight="16dp";
        };
        {
          TextView;
          ellipsize="start";
          textColor=get_theme_color("paratext_color");
          gravity="center";
          Typeface=load_font("common");
          singleLine="true";
          layout_marginLeft="16dp";
          text=project_path;--/未打开工程
          id="project_open_file";
          layout_gravity="left";
          layout_height="20dp";
          textSize="12sp";
          background=Ripple(nil,0x22000000,"方");
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="proj_list_button";
        layout_height="55dp";
        --Visibility="8";
        {
          ImageView;
          layout_height="25dp";
          layout_width="25dp";
          src=load_icon_path("inbox");
          colorFilter=system_title_color();
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="ch_filelist_back_button";
        layout_height="55dp";
        Visibility="8";
        {
          ImageView;
          layout_height="25dp";
          layout_width="25dp";
          src=load_icon_path("undo");
          colorFilter=system_title_color();
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="ch_add_file";
        layout_height="55dp";
        {
          ImageView;
          layout_height="25dp";
          layout_width="25dp";
          src=load_icon_path("add");
          id="ch_add_file_img";
          colorFilter=system_title_color();
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="ch_more_fileoperation_close";
        layout_height="55dp";
        Visibility="8";
        {
          ImageView;
          layout_height="25dp";
          layout_width="25dp";
          src=load_icon_path("undo");
          colorFilter=system_title_color();
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="ch_more_fileoperation";
        layout_height="55dp";
        Visibility="8";
        {
          ImageView;
          layout_height="25dp";
          layout_width="25dp";
          src=load_icon_path("more");
          colorFilter=system_title_color();
        };
      };
      {
        LinearLayoutCompat;
        layout_width="0dp";
        gravity="center";
        id="ch_menu_lay";
        layout_height="0dp";
      };
    };
    {
      LinearLayoutCompat;
      layout_width="fill";
      layout_height="1.04dp";
      backgroundColor=gray_color;
      orientation="vertical";
      layout_marginLeft="10dp";
      layout_marginRight="10dp";
    };
    {
      LinearLayoutCompat;
      orientation="horizontal";
      layout_gravity="center";
      layout_height='56dp';
      layout_marginLeft="8dp";
      layout_marginRight="8dp";
      layout_width="fill";
      Focusable=true;
      FocusableInTouchMode=true;
      {
        EditText;
        id="search_edit";
        hint=gets("search_tip");--输入工程名称...
        layout_width="-1";
        layout_height="-1";
        gravity="left|center";
        background="#00000000";
        textColor=text_color;
        HintTextColor=get_theme_color("paratext_color");
        paddingLeft="8dp";
        textSize="14sp";
        singleLine=true;
        layout_marginTop="8dp";
        layout_marginLeft="8dp";
        layout_marginRight="8dp";
        layout_marginBottom="8dp";
        padding="12dp";
        paddingTop="8dp";
        paddingBottom="8dp";
        layout_height="-1";
        layout_weight="1";
        Typeface=load_font("common");
      };
      {
        ImageView;
        src=load_icon_path("search");
        Visibility="8";
        colorFilter=system_title_color();
        layout_width="25dp";
        layout_height="25dp";
        layout_gravity="center";
        layout_marginRight="10dp";
        id="project_list_search";
      };
    };
    {
      FrameLayout,
      layout_width="fill",
      layout_height="fill",
      {
        LinearLayoutCompat;
        layout_width='fill';
        orientation="vertical";
        layout_height='fill';
        id="list_background";
        {
          SwipeRefreshLayout,
          id="left_sidebar_refresh_layout",
          layout_margin="10dp";
          backgroundColor=get_theme_color("background_color");
          {
            RecyclerView;
            layout_width="fill";
            id="file_rv";
            layout_marigin="10dp";
            layout_height="fill";
          };
        };
      };
    };
  };
  right_sidebar={
    LinearLayoutCompat;
    layout_width="fill";
    layout_height="fill";
    orientation="vertical";
    {
      LinearLayoutCompat;
      layout_width="fill";
      layout_height="fill";
      orientation="vertical";
      backgroundColor=get_theme_color("tool_bar_color");
      {
        LinearLayoutCompat;
        layout_width="fill";
        layout_height="35dp";
        orientation="horizontal";
        layout_marginTop="10dp";
        {
          LinearLayoutCompat;
          layout_weight="1";
          gravity="center";
          layout_height="fill";
          layout_marginLeft="10dp";
          orientation="vertical";
          {
            TextView;
            textSize="20sp";
            text=("MODE");--工程列表
            Typeface=load_font("bold");
            layout_width="fill";
            singleLine=true;
            layout_gravity="center";
            gravity="left";
            textColor=system_title_color();
            layout_marginLeft="20dp";
            layout_marginRight="20dp";
          };
        };
      };
      {
        LinearLayoutCompat;
        layout_height="-1";
        layout_width="-1";
        orientation="vertical";
        backgroundColor=get_theme_color("background_color");
        {
          NestedScrollView;
          layout_height="fill";
          layout_width="fill";
          layout_weight="1";
          VerticalScrollBarEnabled=false;
          OverScrollMode=View.OVER_SCROLL_NEVER;
          {
            LinearLayoutCompat;
            layout_height="-1";
            layout_width="-1";
            orientation="vertical";
            {
              LinearLayoutCompat;
              layout_width="fill";
              layout_height="1.04dp";
              backgroundColor=gray_color;
              orientation="vertical";
              layout_marginLeft="10dp";
              layout_marginRight="10dp";
            };
            {
              LinearLayoutCompat;
              layout_height="-1";
              layout_width="fill";
              orientation="vertical";
              id="grid_view_root_layout";
              layout_marginLeft="8dp";
              layout_marginRight="8dp";
              {
                create_drawer_rv{
                  id="drawer_rv_1",
                  title=gets("code_operation");
                  show=true;
                };
              };
              {
                create_drawer_rv{
                  id="drawer_rv_2",
                  title=gets("project_operation")
                };
              };
              {
                create_drawer_rv{
                  id="drawer_rv_3",
                  title=gets("file_operation")
                };
              };
              {
                create_drawer_rv{
                  id="drawer_rv_4",
                  title=gets("tools_text")
                };
              };
              {
                create_drawer_rv{
                  id="drawer_rv_5",
                  title=gets("other")
                };
              };
            };
          };
        };
        {
          LinearLayoutCompat;
          layout_height="48dp";
          layout_width="-1";
          backgroundColor=get_theme_color("background_color");
          elevation="2dp";
          {
            LinearLayoutCompat;
            layout_height="-1";
            layout_width="-1";
            layout_weight="1";
            gravity="center";
            id="dl_btm_nightmode_btn";--夜间模式按钮
            {
              ImageView;
              src=load_icon_path("brightness_4");
              ColorFilter=pc(text_color);
              layout_width="25dp";
              layout_height="25dp";
              layout_marginRight="4dp";
            };
          };
          {
            LinearLayoutCompat;
            layout_height="-1";
            layout_width="-1";
            layout_weight="1";
            gravity="center";
            id="dl_btm_about_btn";--关于按钮
            {
              ImageView;
              src=load_icon_path("info");
              ColorFilter=pc(text_color);
              layout_width="25dp";
              layout_height="25dp";
              layout_marginRight="4dp";
            };
          };
          {
            LinearLayoutCompat;
            layout_height="-1";
            layout_width="-1";
            layout_weight="1";
            gravity="center";
            id="dl_btm_settings_btn";--设置按钮
            {
              ImageView;
              src=load_icon_path("settings");
              ColorFilter=pc(text_color);
              layout_width="25dp";
              layout_height="25dp";
              layout_marginRight="4dp";
            };
          };
          {
            LinearLayoutCompat;
            layout_height="-1";
            layout_width="-1";
            layout_weight="1";
            gravity="center";
            id="dl_btm_exit_btn";--退出按钮
            {
              ImageView;
              src=load_icon_path("exit");
              ColorFilter=pc(text_color);
              layout_width="25dp";
              layout_height="25dp";
              layout_marginRight="4dp";
            };
          };
        };
      };
    };
  };

  new_right_sidebar={
              LinearLayoutCompat;
              layout_height="-1";
              layout_width="fill";
              orientation="vertical";
              {
                create_drawer_rv{
                  id="drawer_rv_1",
                  title=gets("code_operation");
                  show=true;
                };
              };
              {
                create_drawer_rv{
                  id="drawer_rv_2",
                  title=gets("project_operation")
                };
              };
              {
                create_drawer_rv{
                  id="drawer_rv_3",
                  title=gets("file_operation")
                };
              };
              {
                create_drawer_rv{
                  id="drawer_rv_4",
                  title=gets("tools_text")
                };
              };
              {
                create_drawer_rv{
                  id="drawer_rv_5",
                  title=gets("other")
                };
              };
  };
}