tool_name="Import Analysis"
tool_name_key="import_analysis"
tool_version="2.0"
tool_code="2000"
tool_introduction="Lua导入分析。"
tool_update_log=[[1.修复已知问题。]]
tool_update_time="2022-11-12"
tool_home_activity="main.lua"
tool_value={"lua_path"}
tool_status=true
debugmode=false