layout_assembly={
  drawer_layout={
    ScrollView;
    layout_width="80%w";
    layout_height="fill";
    layout_gravity="left";
    backgroundColor=background_color;
    id="drawer_root_id";
    onClick=function()end;
    {
      LinearLayoutCompat;
      layout_height="fill";
      layout_width="fill";
      orientation="vertical";
      {
        LinearLayoutCompat;
        id="_drawer_header";
        layout_height="wrap";
        layout_width="fill";
        orientation="vertical";
        {
          AppCompatTextView;
          layout_height=get_status_bar_height();
          layout_width="fill";
          backgroundColor=viewshader_color;
        };
        {
          LinearLayoutCompat;
          layout_height="fill";
          layout_width="fill";
          --padding="16dp";
          orientation="vertical";
          {
            AppCompatTextView;
            layout_height="56dp";
            layout_width="wrap";
            id="drawer_title_id";
            textColor=theme_manager.getColorPrimary();
            textSize="20sp";
            paddingLeft="16dp";
            Typeface=load_font("bold");
            gravity="center|left";
          };
        };
      };
      {
        NoScrollListView;
        id="drawer_lv";
        layout_height="fill";
        layout_width="fill";
        DividerHeight=0;
      };
    };
  };
  tool_bar={
    LinearLayoutCompat;
    layout_width="fill";
    orientation="vertical";
    layout_height="56dp";
    backgroundColor=get_theme_color("tool_bar_color");
    id="tool_bar_id";
    {
      LinearLayoutCompat;
      layout_width="fill";
      layout_height="fill";
      gravity="center|left";
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="menu_button";
        layout_height="fill";
        {
          LinearLayoutCompat;
          layout_width="55dp";
          gravity="center";
          id="back_button";
          Visibility="8";
          layout_height="fill";
          onClick=function()
            activity.finish()
          end;
          {
            AppCompatImageView;
            src=load_icon_path("arrow_back");
            ColorFilter=theme_manager.getColorPrimary();
            layout_width="32dp";
            layout_height="32dp";
            padding="4dp";
            id="back_img";
            layout_margin="8dp";
          };
        };
        {
          LinearLayoutCompat;
          layout_width="32dp";
          layout_height="32dp";
          layout_margin="12dp";
          gravity="center";
          orientation="vertical";
          id="menu_img";
          {
            AppCompatTextView;
            layout_width="18.8dp";
            layout_height="2.2dp";
            BackgroundColor=theme_manager.getColorPrimary();
            id="menu_1";
          };
          {
            AppCompatTextView;
            layout_width="18.8dp";
            layout_height="2.2dp";
            BackgroundColor=theme_manager.getColorPrimary();
            layout_marginTop="6";
            id="menu_2";
          };
          {
            AppCompatTextView;
            layout_width="18.8dp";
            layout_height="2.2dp";
            BackgroundColor=theme_manager.getColorPrimary();
            layout_marginTop="6";
            id="menu_3";
          };
        };
      };
      {
        LinearLayoutCompat;
        layout_weight="1";
        gravity="center";
        layout_height="fill";
        orientation="vertical";
        {
          AppCompatTextView;
          textColor=theme_manager.getColorPrimary();
          textSize="18sp";
          id="main_title_id";
          singleLine=true;
          layout_width="fill";
          gravity="center|left";
          ellipsize="start";
          Typeface=load_font("bold");
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="search_button";
        layout_height="fill";
        Visibility="8";
        {
          AppCompatImageView;
          src=load_icon_path("search");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp";
          layout_height="32dp";
          padding="4dp";
          id="search_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="more_button";
        layout_height="fill";
        Visibility="8";
        {
          AppCompatImageView;
          src=load_icon_path("more_vert");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp";
          layout_height="32dp";
          padding="4dp";
          id="more_img";
          layout_margin="8dp";
        };
      };
      {
        AppCompatTextView;
        id="more_lay";
        layout_width="0";
        layout_height="0";
        layout_gravity="top";
      };
    };
  };

  search_bar={
    LinearLayoutCompat;
    layout_width="fill";
    orientation="vertical";
    layout_height="56dp";
    backgroundColor=get_theme_color("tool_bar_color");
    id="search_bar_id";
    Visibility="8";
    {
      LinearLayoutCompat;
      layout_width="fill";
      layout_height="fill";
      gravity="center|left";
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="search_bar_cancel_button";
        layout_height="fill";
        {
          AppCompatImageView;
          src=editor_icons("cancel");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp";
          layout_height="32dp";
          padding="4dp";
          id="search_bar_cancel_button_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_weight="1";
        gravity="center";
        layout_height="fill";
        orientation="vertical";
        {
          AppCompatEditText;
          textColor=text_color;
          HintTextColor=get_theme_color("paratext_color");
          gravity="left";
          Typeface=load_font("common");
          backgroundColor="0";
          id="search_bar_edit";
          layout_gravity="center";
          layout_width="fill";
          textSize="20sp";
          singleLine="true";
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="search_bar_search_button";
        layout_height="fill";
        {
          AppCompatImageView;
          src=load_icon_path("search");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp";
          layout_height="32dp";
          padding="4dp";
          id="search_bar_search_img";
          layout_margin="8dp";
        };
      };
    };
  };
  editor_top_bar={
    LinearLayoutCompat;
    layout_width="fill",
    orientation="vertical";
    layout_height="56dp",
    backgroundColor=get_theme_color("tool_bar_color");
    id="tool_bar_id",
    {
      LinearLayoutCompat;
      layout_width="fill",
      layout_height="fill",
      gravity="center|left";
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="folder_button";
        layout_height="fill";
        {
          ImageView;
          src=load_icon_path("folder");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="folder_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="menu_button";
        layout_height="fill";
        Visibility="8";
        {
          LinearLayoutCompat;
          layout_width="55dp";
          gravity="center";
          id="menu_back_button";
          Visibility="8";
          layout_height="fill";
          onClick=system_incident["finish"];
          {
            ImageView;
            src=load_icon_path("arrow_back");
            ColorFilter=theme_manager.getColorPrimary();
            layout_width="32dp",
            layout_height="32dp",
            padding="4dp";
            id="menu_back_img";
            layout_margin="8dp";
          };
        };
        {
          LinearLayoutCompat;
          layout_width="32dp";
          layout_height="32dp";
          layout_margin="12dp";
          gravity="center";
          orientation="vertical";
          id="menu_img";
          {
            TextView;
            layout_width="18.8dp";
            layout_height="2.2dp";
            BackgroundColor=theme_manager.getColorPrimary();
            id="menu_1";
          };
          {
            TextView;
            layout_width="18.8dp";
            layout_height="2.2dp";
            BackgroundColor=theme_manager.getColorPrimary();
            layout_marginTop="6";
            id="menu_2";
          };
          {
            TextView;
            layout_width="18.8dp";
            layout_height="2.2dp";
            BackgroundColor=theme_manager.getColorPrimary();
            layout_marginTop="6";
            id="menu_3";
          };
        };
      };
      {
        LinearLayoutCompat;
        layout_weight="1";
        gravity="center";
        layout_height="fill";
        orientation="vertical";
        id="title_background";
        {
          TextView;
          Selected=true;--文本可选
          textColor=theme_manager.getColorPrimary();
          textSize="20sp";
          id="main_title_id";
          SingleLine=true;
          layout_width="-1",
          layout_gravity="left";
          Typeface=load_font("bold");
          background=Ripple(nil,0x22000000,"方");
          onClick=system_incident["view_copy"]
        };
        {
          TextView;
          ellipsize="start";
          id="opened_file";
          Typeface=load_font("common");
          layout_gravity="left";
          gravity="center|left";
          textSize="12sp";
          SingleLine=true;
          textColor=get_theme_color("paratext_color");
          background=Ripple(nil,0x22000000,"方");
          onClick=system_incident["view_copy"]
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="layout_helper_button";
        layout_height="fill";
        {
          ImageView;
          src=load_icon_path("panorama");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="layout_helper_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="play_button";
        layout_height="fill";
        {
          ImageView;
          src=load_icon_path("play_arrow");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="play_img";
          layout_margin="8dp";
        };
      };

      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="undo_button";
        layout_height="fill";
        {
          ImageView;
          src=load_icon_path("undo");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="undo_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="redo_button";
        layout_height="fill";
        Visibility="8";
        {
          ImageView;
          src=load_icon_path("redo");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="redo_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="more_button";
        layout_height="fill";
        {
          ImageView;
          src=load_icon_path("more");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="more_img";
          layout_margin="8dp";
        };
      };
      {
        TextView;
        id="more_lay";
        layout_width="0",
        layout_height="0",
        layout_gravity="top";
      };
    };
  };

  editor_control_bar={
    LinearLayoutCompat;
    layout_width="fill",
    orientation="vertical";
    layout_height="56dp",
    backgroundColor=get_theme_color("tool_bar_color");
    id="control_bar_id",
    Visibility="8";
    {
      LinearLayoutCompat;
      layout_width="fill",
      layout_height="fill",
      gravity="center|left";
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="cancel_button";
        layout_height="fill";
        {
          ImageView;
          src=editor_icons("cancel");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="cancel_button_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_weight="1";
        gravity="center";
        layout_height="fill";
        orientation="vertical";
        {
          TextView;
          textColor=theme_manager.getColorPrimary();
          textSize="20sp";
          id="control_bar_title";
          SingleLine=true;
          layout_width="-1",
          gravity="center|left";
          Typeface=load_font("bold");
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="select_all_button";
        layout_height="fill";
        {
          ImageView;
          src=editor_icons("select_all");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="select_all_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="cut_button";
        layout_height="fill";
        {
          ImageView;
          src=editor_icons("cut");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="cut_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="copy_button";
        layout_height="fill";
        {
          ImageView;
          src=editor_icons("copy");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="copy_img";
          layout_margin="8dp";
        };
      };
      {
        LinearLayoutCompat;
        layout_width="55dp";
        gravity="center";
        id="paste_button";
        layout_height="fill";
        {
          ImageView;
          src=editor_icons("clipboard");
          ColorFilter=theme_manager.getColorPrimary();
          layout_width="32dp",
          layout_height="32dp",
          padding="4dp";
          id="paste_img";
          layout_margin="8dp";
        };
      };
    };
  };
}