appname="文件管理"
tool_name="File Manager"
tool_name_key="file_manager_text"
tool_version="1.0"
tool_code="1000"
tool_update_time="2023-07-18"
tool_home_activity="main.lua"
tool_status=true
support_open_by_dialog=true
debugmode=false
debugmode=false
tool_introduction="File Manager"
tool_update_log=[[]]