tool_name="Lua Course"
tool_name_key="lua_course"
tool_version="2.0"
tool_code="2000"
tool_introduction="Lua教程手册。"
tool_update_log=[[1.修复已知问题。]]
tool_update_time="2022-11-12"
tool_home_activity="main.lua"
tool_status=true
support_open_by_dialog=true
debugmode=false