tool_name="Project Info Editor"
tool_name_key="project_info"
tool_version="2.0"
tool_code="2000"
tool_introduction="工程属性编辑器"
tool_update_log=[[1.修复已知问题。]]
tool_update_time="2022-11-12"
tool_home_activity="main.lua"
tool_status=true
tool_value={"proj_path"}
must_value=true
debugmode=false